### ISSUE TITLE
real image mix

### ISSUE THREAD

**Issue by rainsoulsrx** [rolux/stylegan2encoder#5]
hi, thank you for your work, I have a question when doing style mixing between two real images,
In stylgan1, I chose range(8,18), which performs well, but in stylegan2, I use the same param, the results turn out to be bad.
I wonder, the scale in stylegan 1 and 2 is represent different meaning?

**Comment by dimitry12** [comment]
@rainsoulsrx I suspect, semantic content of style-layers changed in StyleGAN2. Were you able to find the range which works for StyleGAN2?

**Comment by b4nn3d** [comment]
can you share an how to for create and mix images from npy files?

**Comment by rolux** [comment]
Style mixing works as demonstrated in the original StyleGAN2 repo. Nothing has changed there. See [this comment](https://github.com/rolux/stylegan2encoder/issues/2#issuecomment-570548948) for orientation.

If, however, you're mixing latents from encoder/projector results, this may not work as expected. In case the distance of your latents to w_avg becomes too large, they lose their "semantic content" altogether. For more, read the thread linked above.

**Comment by shahik** [comment]
@rainsoulsrx Plz share the code for npy files style-mixing ?
