### ISSUE TITLE
Render npy not showing correct image

### ISSUE THREAD

**Issue by miolamio** [rolux/stylegan2encoder#8]
Hi! Great work, thank you!

I was wondering if you could post an example of how to render an image from NPY file, I tried to load an image and generate it using Gs.run(latent1, None), but it seems I get another image as a result.

Thanks!

**Comment by rolux** [comment]
@miolamio: I guess you'd have to show me the code you're running.

**Comment by miolamio** [comment]
@rolux, I managed to render a correct image using this code here with slight modifications! All works, thank you for your support!

**Comment by b4nn3d** [comment]
Hello there, what I'm doing wrong?

latent = np.load("/content/drive/My Drive/stylegan2encoder/eli_750lr015/11247072_10206908671705487_6505812163240309958_o_02.npy")

_G, _D, Gs = pretrained_networks.load_networks(network_pkl)
noise_vars = [var for name, var in Gs.components.synthesis.vars.items() if name.startswith('noise')]

Gs_kwargs = dnnlib.EasyDict()
Gs_kwargs.output_transform = dict(func=tflib.convert_images_to_uint8, nchw_to_nhwc=True)
Gs_kwargs.randomize_noise = False

images = Gs.run(latent, None, **Gs_kwargs) # [minibatch, height, width, channel]
PIL.Image.fromarray(images[0], 'RGB').save('/content/drive/My Drive/stylegan2encoder/myimage.jpg')

**Comment by WJ-Lai** [comment]
> @rolux, I managed to render a correct image using this code here with slight modifications! All works, thank you for your support!

Hi, could you please tell me how you did it? I encounter the same problem. 
I use npy file to th generator but the image was not the same as the output image.

**Comment by Pinnh** [comment]
It happens because optimization is not only latent but noises , when regularity of noises is small，some information is encoded in noises，the output image is produced by latent and noise, if you use only latent to generate image ,these two images are different

**Comment by robbaker292** [comment]
@Pinnh I have a similar issue. The numpy file produced by `project_images.py` is shape ` (18,512)`  whereas StyleGAN2 uses `(1,512)`. Extracting each of the 18 slices all produce different images and none of these are even close to the input image.

Along with the latents, do I need to extract something else, or combine each slice in some way? I was expecting `project_images.py` to produce a npy array I could insert straight back into StyleGAN, but it seems not.

**Comment by woctezuma** [comment]
No. That is related to #21.

**Comment by woctezuma** [comment]
No. Your 18x512 array `w` is valid and can be fed to `Gs.components.synthesis.run()`. That is related to #21. Here is [a Gist](https://gist.github.com/woctezuma/71b89d6a61e373ddec08a5520e86055b).

**Comment by robbaker292** [comment]
> No. Your 18x512 array `w` is valid and can be fed to `Gs.components.synthesis.run()`. That is related to #21. Here is [a Gist](https://gist.github.com/woctezuma/71b89d6a61e373ddec08a5520e86055b).

Thanks, that makes a bit more sense. However, I'm asking if the latents that represent that new image are available in `(1,512)` (perhaps as an output of synthesis?) for inserting back into the original stylegan2 code i.e. back in the `images = Gs.run(z, None, **Gs_kwargs)` line in `run_generator.py` of StyleGAN2?

**Comment by woctezuma** [comment]
You can get a 1x512 array `w` (not `z`) with the projection procedure available in the **official** StyleGAN2 repository.

The 18x512 array `w^+` which you obtained using the projection procedure in this repository is the result of a trick to get higher image fidelity to the target, and that is all there is to it.

**Comment by robbaker292** [comment]
Thanks. How does one convert `w` to `z`?

**Comment by woctezuma** [comment]
There is no built-in method to do so. It is an inverse problem.

**Comment by robbaker292** [comment]
Okay, well thanks for your help 👍

**Comment by woctezuma** [comment]
For reference: https://github.com/minyoungg/pix2latent

![Text](https://i.imgur.com/kQWC8IR.png)
![Results](https://i.imgur.com/S8CDpHM.jpg)

**Comment by Pinnh** [comment]
One thing that I want to mention is Latent can't encode every thing in StyleGAN, so when you do inverse optimization , there are also some distances between input image and image that generate by latent of StyleGAN, say faces' cosine similarity(CosSim), so when you use Latent and Noises to optimize the CosSim you can get even 99.5% closer to input but when you edit the latent to do the warp transform, you will find that the details are position invariant 

Ref paper: Image2StyleGAN++: How to Edit the Embedded Images
